package com.yfy.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adminDbDaoConfig;
    private final DaoConfig keyValueDbDaoConfig;
    private final DaoConfig mainIndexDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AdminDbDao adminDbDao;
    private final KeyValueDbDao keyValueDbDao;
    private final MainIndexDao mainIndexDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adminDbDaoConfig = daoConfigMap.get(AdminDbDao.class).clone();
        adminDbDaoConfig.initIdentityScope(type);

        keyValueDbDaoConfig = daoConfigMap.get(KeyValueDbDao.class).clone();
        keyValueDbDaoConfig.initIdentityScope(type);

        mainIndexDaoConfig = daoConfigMap.get(MainIndexDao.class).clone();
        mainIndexDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        adminDbDao = new AdminDbDao(adminDbDaoConfig, this);
        keyValueDbDao = new KeyValueDbDao(keyValueDbDaoConfig, this);
        mainIndexDao = new MainIndexDao(mainIndexDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(AdminDb.class, adminDbDao);
        registerDao(KeyValueDb.class, keyValueDbDao);
        registerDao(MainIndex.class, mainIndexDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        adminDbDaoConfig.clearIdentityScope();
        keyValueDbDaoConfig.clearIdentityScope();
        mainIndexDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AdminDbDao getAdminDbDao() {
        return adminDbDao;
    }

    public KeyValueDbDao getKeyValueDbDao() {
        return keyValueDbDao;
    }

    public MainIndexDao getMainIndexDao() {
        return mainIndexDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
